config/routes.rb
GGT::Application.routes.draw do
  resources :users, :posts
  resources :events, only: :index
  resources :avatars, only: [:edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'posts#index'

  match '/register', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/usercp', to: 'avatars#edit'

  match '/users/:id/events' => 'events#user_events'
end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :event_type, :user_id1, :user_id2, :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id, :visible

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :banned, :email, :password, :password_confirmation, :username, :postcount
  has_secure_password

  has_many :posts

  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, length: { maximum: 26, minimum: 3 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 3 }
  validates :password_confirmation, presence: true

  private
  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include EventsHelper
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
	def edit
	end

	def update
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all(:order => 'created_at DESC')
	end

	def user_events
		@events = Event.where('user_id1 = :id OR user_id2 = :id', {:id => params[:id]}).order('created_at DESC')
		render 'index'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#before_filter :not_banned
	before_filter :logged_in_user, only: [:new, :create]
	def index
		@posts = Post.paginate(page: 1)
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(params[:post])

		current_user.update_attribute(:postcount, current_user.postcount + 1)

		if @post.save
			redirect_with_flash("Post successfully created", :success)
		else
			render 'new'
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_filter :not_banned
	before_filter :not_signed_in_user, only: [:new, :create]

	def new
	end

	def create
		user = User.find_by_username(params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			log_in user
			flash[:success] = "You have successfully logged in"
			redirect_back_or root_path
		else
			flash.now[:error] = "Invalid username/password combination"
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_with_flash("You have successfully logged out", :success)
	end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :not_banned
	before_filter :not_signed_in_user, only: [:new, :create]
	before_filter :logged_in_user, only: [:edit, :update]
	before_filter :correct_user_or_admin, only: [:edit, :update]
	before_filter :admin_user, only: :destroy

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			log_in @user
			event_log(1, @user.id)
			redirect_with_flash("You have successfully registered", :success)
		else
			render 'new'
		end
	end

	def update
		if @user.update_attributes(params[:user])
			event_log(6, current_user.id, @user.id)
			log_in @user if current_user? @user
			redirect_with_flash("Profile successfully updated", :success, @user)
		else
			render 'edit'
		end
	end

	def destroy
	end

	private
		def correct_user_or_admin
			@user = User.find(params[:id])
			unauthorized unless current_user?(@user) || current_user.admin?
		end

		def admin_user
			unauthorized unless current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		base_title = "The Gift Giving Thread"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def dispatch_event(event)
		event_name = event_by_name(event.event_type)
		send("event_#{event_name}", event)
	end

	def event_log(event_type = 0, user_id1 = 0, user_id2 = 0, post_id = 0)
		@event = Event.new(:event_type => event_type, :user_id1 => user_id1, :user_id2 => user_id2, :post_id => post_id)
		@event.save
	end

private
	def event_by_name(id)
		events = ['unknown', 'register', 'permaban', 'unban', 'trash', 'untrash', 'usermod', 'edit']
		events[id]
	end

	def pull_user(user_id)
		@users = User.all unless defined? @users
		@users[(user_id)-1]
	end

	def ago(event)
		time_ago_in_words(event.created_at) + ' ago'
	end

	def link_to_post(text, event)
		link_to(text, :controller => 'posts', :action => 'show', :id => event.post_id)
	end

	def link_to_user(user)
		t_user = pull_user(user)
		link_to(t_user.username, t_user)
	end

	def event_unknown(event)
		'An unknown event occured ' + ago(event)
	end

	def event_register(event)
		link_to_user(event.user_id1) + ' registered ' + ago(event)
	end

	def event_permaban(event)
		link_to_user(event.user_id1) + ' permabanned ' + link_to_user(event.user_id2) + ' for ' + link_to_post('this post', event) + ' ' + ago(event)
	end

	def event_unban(event)
		link_to_user(event.user_id1) + ' unbanned ' + link_to_user(event.user_id2) + ' ' + ago(event)
	end

	def event_trash(event)
		link_to_user(event.user_id1) + ' trashed ' + link_to_user(event.user_id2) + '\'s ' + link_to_post('post', event) + ' ' + ago(event)
	end

	def event_untrash(event)
		link_to_user(event.user_id1) + ' untrashed ' + link_to_user(event.user_id2) + '\'s ' + link_to_post('post', event) + ' ' + ago(event)
	end

	def event_usermod(event)
		link_to_user(event.user_id1) + ' modified ' + link_to_user(event.user_id2) + '\'s account information ' + ago(event)
	end

	def event_edit(event)
		link_to_user(event.user_id1) + ' edited ' + link_to_user(event.user_id2) + '\'s post ' + link_to_post('here', event) + ' ' + ago(event)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def log_out
		current_user = nil
		cookies.delete(:remember_token)
	end

	def not_banned
		unauthorized if current_user.banned? unless !logged_in?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end

	def store_location
		session[:return_to] = request.fullpath
	end

	def redirect_with_flash(message, error = :error, path = root_path)
		flash[error] = message
		redirect_to path
	end

	def not_signed_in_user
		unauthorized if logged_in?
	end

	def logged_in_user
		unless logged_in?
			store_location
			redirect_with_flash("You must first log in to access that page", :error, login_path)
		end
	end

	def unauthorized
		redirect_with_flash("You are not permitted to access that page")
	end

	private
		def user_from_remember_token
			remember_token = cookies[:remember_token]
			User.find_by_remember_token(remember_token) unless remember_token.nil?
		end

		def clear_return_to
			session.delete(:return_to)
		end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% @events.each do |event| %>
	<%= dispatch_event(event) %><br />
<% end %>

app/views/events/new.html.erb
<% provide(:title, "Add Event") %>
<h1>Add Event</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@event) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :event_type %>
			<%= f.text_field :event_type %>

			<%= f.label :user_id1 %>
			<%= f.text_field :user_id1 %>

			<%= f.label :user_id2 %>
			<%= f.text_field :user_id2 %>

			<%= f.label :post_id %>
			<%= f.text_field :post_id %>

			<%= f.submit "Add Event", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://github.com/TehWhale/GGT">The Gift Giving Thread</a>
		by <a href="http://erppy.co/">TehWhale</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Statistics", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "The Gift Giving Thread", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Events", events_path %></li>
					<li><%= link_to "Ratings", '#' %></li>
					<li><%= link_to "Search", '#' %></li>
					<li><%= link_to "Latest Post", '#' %></li>
					<% if logged_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%= current_user.username %> <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li><%= link_to 'My Events', :controller => 'events', :action => 'user_events', :id => current_user.id %></li>
								<li class="divider"></li>
								<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log In", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.google.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		
		<%= debug(current_user) if Rails.env.development? && logged_in? %>
	</div>
</body>
</html>

app/views/posts/index.html.erb
<div id="mainbody">
	<div class="ds_container">
		<div class="grid_12">
			<div class="pagesection">
				<%= will_paginate %>
			</div>
			<div id="forumposts">
				<% @posts.each do |post| %>
				<div class="windowbg">
					<span class="topslice"><span></span></span>
					<div class="post_wrapper">
						<div class="poster">
							<h4>
								<%= link_to post.user.username, post.user %>
							</h4>
							<ul class="reset smalltext">
								<!--<li class="title">depressed insomniac</li>-->
								<li class="avatar">
									<a href="#">
										<!--<img class="avatar" src="http://facepunch.com/image.php?u=239086" alt="">-->
									</a>
								</li>
								<li class="postcount">Posts: <%= post.user.postcount %></li>
								<li class="profile">
									<ul>
										<li><a href="#" title="Windows 7" class="new_win"><img src="http://facepunch.com/fp/browser/windows7.png" alt="OS"></a></li>
										<li><a href="#" title="Google Chrome" class="new_win"><img src="http://facepunch.com/fp/browser/chrome.png" alt="Browser"></a></li>
										<li><a href="#" title="Events" class="new_win"><img src="http://www.facepunch.com/fp/navbar/events.png" alt="Events"></a></li>
										<li><a href="#" title="Report" class="new_win"><img src="http://www.facepunch.com/fp/report.png" alt="Report"></a></li>
									</ul>
								</li>
							</ul>
						</div>
						<div class="postarea">
							<div class="flow_hidden">
								<div class="keyinfo">
									<div class="smalltext">« <strong>Post #<%= link_to post.id, post %></strong> <%= time_ago_in_words(post.created_at) %> ago »</div>
								</div>
							</div>
							<div class="post">
								<div class="inner">
									<%= simple_format(post.content) %>
								</div>
							</div>
						</div>
						<div class="moderatorbar">
							<!--<div class="smalltext modified">
								Last edited at 11:47am on July 24th, 2012
							</div>
							<!--<div class="signature">
								<div align="center">
									I am the HOBO
								</div>
							</div>-->
						</div>
					</div>
					<span class="botslice"><span></span></span>
				</div>
				<hr class="post_separator">
				<% end %>
			</div>
			<a id="lastPost"></a>
			<div class="pagesection">
				<div class="pagelinks floatleft">Pages: [<strong>1</strong>]</div>
			</div>
			<br class="clear">
		</div>
		<div class="clr"></div>
	</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'Makea Post') %>
<h1>Makea Post</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@post) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :content %>
			<%= f.text_area :content %>
			<%= f.submit "Posty Post", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/statics/home.html.erb
<h1>I'm serving up the static content aww yeah</h1>

app/views/users/_fields.html.erb
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Edit User</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "All Users") %>
<h1>All Users</h1>

<ul class="users">
	<% @users.each do |user| %>
	<li>
		<%= link_to user.username, user %>
		<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to "delete", user, method: :delete, confirm: "Are you sure you want to destroy this user?" %>
		<% end %>
	</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= render 'fields', f: f %>
			<%= f.submit "Register Now", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
	<div class="span12">
		<h1><%= @user.username %></h1>
		<h3><%= link_to('Events', :controller => 'events', :action => 'user_events', :id => @user.id) %></h3>
		<h3><%= @user.email %></h3>
		<h4><%= @user.id %>
		<h5>Registered <%= time_ago_in_words(@user.created_at) %> ago</h5>
		<h5>Last edited <%= time_ago_in_words(@user.updated_at) %> ago</h5>
		<h5>Admin? <%= @user.admin %></h5>
		<h5>Banned? <%= @user.banned %></h5>
	</div>
</div>